services:
  mysql:  ## 应用名字
    container_name: mysql ## 容器名字
    image: mysql:8.0 ## 镜像名字
    ports: ## 端口映射
      - "3306:3306"
    environment: ## 环境变量
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DataBASE=wordpress
    volumes: ## 卷映射
      - mysql-data:/var/lib/mysql
      - /app/myconf:/etc/mysql/conf.d
    restart: always ## 重启策略
    networks: ## 网络
      - blog
  wordpress: ## 应用名字
    image: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - blog
    depends_on: ## 依赖
      - mysql ## 应用名字
volumes: ## 卷映射声明
  mysql-data:
  wprdpress:
networks: ## 网络声明（内部配置不用管）
  blog:
